name: todo_app_CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.0

      - name: log in to docker hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{secrets.USER_NAME_DOCKER_HUB}} 
          password: ${{secrets.TOCKEN_DOCKER_HUB}}
      
        env:
          REPOSITORY: todo_app
          IMAGE_TAG: latest
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.USER_NAME_DOCKER_HUB }}/$REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.TOCKEN_DOCKER_HUB}}/$REPOSITORY:$IMAGE_TAG

